language: node_js
node_js:
  - "8"
install:
  - npm install
  - npm run build
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: "$awskey"
    secret_access_key: "$awssecret"
    bucket: "dev.icasting.io"
    acl: public_read
    local_dir: dist
    region: eu-west-1
    on:
      branch: dev
  - provider: s3
    skip_cleanup: true
    access_key_id: "$awskey"
    secret_access_key: "$awssecret"
    bucket: "icasting.io"
    acl: public_read
    local_dir: dist
    region: eu-west-1
    on:
      tags: true
